name       : pycangjie
version    : 1.2
release    : 2
source     :
    - https://github.com/Cangjians/pycangjie/releases/download/v1.2/cangjie-1.2.tar.xz : bc9115904f65581a11e43044c83e999e583468d1bb98c04b33ea059205e07c10
license    : LGPL-3.0
component  : programming.python
summary    : This is a Python wrapper to libcangjie, the library implementing the
    Cangjie input method.
description: |
    This is a Python wrapper to libcangjie, the library implementing the Cangjie input method.
builddeps  :
    - pkgconfig(cangjie)
    - pkgconfig(python3)
    - cython
setup      : |
    %patch -p1 < $pkgfiles/cython.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
